name: Mirroring

on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-NWP-400-PAR-4-1-myftp-lindon.aliu.git
  EXECUTABLE: myftp

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: .#
        run: |
          FILE=$(find . -name "\#*\#")
          if [[ -n "$FILE" ]]; then
          echo "::error file=$FILE,line=1,col=5,endColumn=7,title=Unwanted file detected::$FILE"
          fi
      - name: .~
        run: |
          FILE=$(find . -name *~)
          if [[ -n "$FILE" ]]; then
          echo "::error file=$FILE,line=1,col=5,endColumn=7,title=Unwanted file detected::$FILE"
          fi
      - name: .pain_au_chocolat
        run: |
          FILE=$(find . -name *pain_au_chocolat*)
          if [[ -n "$FILE" ]]; then
          echo "::error file=$FILE,line=1,col=5,endColumn=7,title=Unwanted file detected::$FILE"
          fi
      - name: .o
        run: |
          FILE=$(find . -name *.o)
          if [[ -n "$FILE" ]]; then
          echo "::error file=$FILE,line=1,col=5,endColumn=7,title=Unwanted file detected::$FILE"
          fi
      - name: .a
        run: |
          FILE=$(find . -name *.a)
          if [[ -n "$FILE" ]]; then
          echo "::error file=$FILE,line=1,col=5,endColumn=7,title=Unwanted file detected::$FILE"
          fi
      - name: .so
        run: |
          FILE=$(find . -name *.so)
          if [[ -n "$FILE" ]]; then
          echo "::error file=$FILE,line=1,col=5,endColumn=7,title=Unwanted file detected::$FILE"
          fi
      - name: .gcno
        run: |
          FILE=$(find . -name *.gcno)
          if [[ -n "$FILE" ]]; then
          echo "::error file=$FILE,line=1,col=5,endColumn=7,title=Unwanted file detected::$FILE"
          fi
      - name: .gcda
        run: |
          FILE=$(find . -name *.gcda)
          if [[ -n "$FILE" ]]; then
          echo "::error file=$FILE,line=1,col=5,endColumn=7,title=Unwanted file detected::$FILE"
          fi
      - name: .gcov
        run: |
          FILE=$(find . -name *.gcov)
          if [[ -n "$FILE" ]]; then
          echo "::error file=$FILE,line=1,col=5,endColumn=7,title=Unwanted file detected::$FILE"
          fi
  check_program_compilation:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: make
      - run: make clean
  run_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container:
      image:  epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: make tests_run
  push_to_mirror:
    runs-on: ubuntu-latest
    needs: [check_repository_cleanliness, check_program_compilation, run_tests]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
